app: "GNN Assembly Pipeline"

#data: data
#refs: data/references
#out: 
#overfit: False

species: test_test1
simulator:
  coverage: 32
assembler:
  name: LJA
  params:
    threads: 8
    k: 31
    K: 8
